--CREATE TABLE CLIENTES(
--ID_CLIENTE INTEGER PRIMARY KEY AUTOINCREMENT,
--NOMBRE TEXT,
--CORREO TEXT,
--TELEFONO TEXT
--);

--CREATE TABLE PRODUCTO(
--"ID_PRODUCTO" INTEGER PRIMARY KEY AUTOINCREMENT,
--"PRODUCTO" TEXT,
--"PRECIO" REAL,
--"STOCK" INTEGER
--);

--CREATE TABLE PEDIDO(
--"ID_PEDIDO" INTEGER PRIMARY KEY AUTOINCREMENT,
--"ID_CLIENTE" INTEGER,
--"FECHA" TEXT,
--"TOTAL" REAL,
--FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
--);

--CREATE TABLE DETALLESPEDIDO(
--"ID_DETALLES" INTEGER PRIMARY KEY AUTOINCREMENT,
--"-ID_PEDIDO" INTEGER,
--"ID_PRODUCTO" INTEGER,
--"CANTIDAD" INTEGER,
--"SUBTOTAL" REAL,
--FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
--FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
--);

--INSERT INTO CLIENTES("NOMBRE", "CORREO", "TELEFONO")
--VALUES ( "Emilio", "emilio@gmail.com", "312378361")

--INSERT INTO CLIENTES("NOMBRE", "CORREO", "TELEFONO")
--VALUES ("Santiago", "santi.r@hotmail.com", "312534761")Ç

--INSERT INTO PRODUCTO("PRODUCTO", "PRECIO", "STOCK")
--VALUES ("HAMBURGUESA SENCILLA", "23000", "3")

--INSERT INTO PRODUCTO("PRODUCTO", "PRECIO", "STOCK")
--VALUES ("HAMBURGUESA DOBLE", "29000", "5")

--INSERT INTO PRODUCTO("PRODUCTO", "PRECIO", "STOCK")
--VALUES ("PERRO", "18000", "4")

--INSERT INTO PEDIDO("ID_CLIENTE", "FECHA", "TOTAL")
--VALUES("2", "18-02-2025","33000")

--INSERT INTO DETALLESPEDIDO ("ID_PEDIDO", "ID_PRODUCTO", "CANTIDAD", "SUBTOTAL")
--VALUES("1", "2", 1, 33000)

-- SELECT * FROM CLIENTES










